// Generated by https://quicktype.io

export interface MatchRequest {
    matchId: number;
    events:  EventRequest[];
}

export interface EventRequest {
    playerParticipantId: number;
    type:                string;
    quantity:            number;
}

export interface MatchDateResponse {
    newDate:string;
}