// Generated by https://quicktype.io

export interface TeamRequest {
    color: string;
    name: string;
    players: PlayerRequest[];
}

export interface PlayerRequest {
    name: string;
    lastName: string;
    isCaptain: boolean;
    isGoalKeeper: boolean;
    number: number;
}
